name: Feather
options:
  bundleIdPrefix: "thewonderofyou.Feather"
targets:
  Replay:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Sources
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "thewonderofyou.Feather.VR242P5QF6"
      INFOPLIST_FILE: Sources/Info.plist
      MARKETING_VERSION: "1.0.0"
      CURRENT_PROJECT_VERSION: "1"
