name: Build iOS App
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install xcodegen
        run: brew install xcodegen

      - name: Generate Project
        run: xcodegen generate

      - name: Archive App
        run: |
          xcodebuild archive \
          -project Replay.xcodeproj \
          -scheme Replay \
          -archivePath Replay.xcarchive \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO

      - name: Package IPA Manually
        run: |
          mkdir Payload
          cp -r Replay.xcarchive/Products/Applications/Replay.app Payload/
          zip -r Replay.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: Replay-App
          path: Replay.ipa
