name: Build iOS App

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install xcogen
        run: brew install xcodegen

      - name: Generate Project
        run: xcodegen generate

      - name: Build App
        run: |
          xcodebuild build \
          -project Replay.xcodeproj \
          -scheme Replay \
          -destination 'generic/platform=iOS' \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
